# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Bethere24' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SVProgressHUD'

  # Pods for Bethere24

  target 'Bethere24Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bethere24UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
