# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Bethere24' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SVProgressHUD'
pod 'SwiftyJSON'
pod 'SideMenuController', '~> 0.1.6'
pod 'UIColor_Hex_Swift', '~> 2.1'
# pod 'KMPlaceholderTextView', '~> 1.2.2'

  # Pods for Bethere24

  target 'Bethere24Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bethere24UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
